apiVersion: v1
kind: Service
metadata:
  name: add-api-service
  labels:
    app: add-api
spec:
  type: LoadBalancer
  selector:
    app: add-api
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
