apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: add-api-hpa
  namespace: default # important
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: add-api #<your-deployment-name>
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70