apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: add-api-hpa
  namespace: default # important
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: add-api #<your-deployment-name>
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60  # Prevents immediate scale-ups
#kubectl describe hpa add-api-hpa
#kubectl get hpa add-api-hpa -w
#kubectl scale deployment add-api --replicas=1

#This continuously consumes CPU cycles.
#kubectl exec -it <frontend-pod-name> -- /bin/sh
#after inside
#while true; do :; done

#This allocates 200MB of memory rapidly.
#kubectl exec -it add-api-<pod-id> -- /bin/sh -c "head -c 200M < /dev/urandom > /dev/null &"