apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: default
spec:
  containers:
  - name: load-generator
    image: busybox  # Use a lightweight image
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache stress
        stress --cpu 8 --timeout 600s
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

#kubectl get deployment add-api
#kubectl get hpa add-api-hpa
#kubectl get pods -l add-api